language: python

python:
  - 2.6
  - 2.7

before_install:
  - sudo apt-get install -y libxml2-dev libxslt-dev

script: python manage.py test --settings=example_project.settings_test --verbosity=2
install: 
  - pip install -r requirements_test.txt --use-mirrors
  - pip install -r requirements.txt --use-mirrors